trigger:
  branches:
    include:
      - main

pr:
  - main

resources:
  repositories:
    - repository: templates
      type: github
      name: mauriciomutte/fe-infra
      endpoint: github.com
      ref: main

extends:
  template: azure-templates/frontend.yaml@templates